# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [4]:
arreglo_1 = np.zeros(12)
arreglo_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arreglo_2 = np.zeros(10)
arreglo_2[5] = 10
arreglo_2

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.])

In [8]:
arreglo_3 = np.arange(10,49+1,1)
arreglo_3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
arreglo_4 = np.arange(0, 9, 1).reshape((3, 3))
arreglo_4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
from numpy import random

arreglo_5 =random.randint(1000, size=(100))
print(f"Media: {np.mean(arreglo_5)}")
print(f"Varianza: {np.var(arreglo_5)}")

Media: 473.47
Varianza: 75837.38909999999


In [18]:
suma = np.sum(arreglo_5)
media = suma / arreglo_5.size
media

473.47

In [20]:
# Cómo se calcula la varianza ------------------------------------------------
# Calcula la media de los datos.
# Encuentra la diferencia de cada punto de datos con respecto al valor medio.
# Eleva al cuadrado cada uno de estos valores.
# Suma todos los valores elevados al cuadrado.
# Divide esta suma de cuadrados entre n – 1 (para una muestra) o N (para la población).

sumatoria = arreglo_5 - np.mean(arreglo_5)
sumatoria = sumatoria ** 2
sumatoria_2 = np.sum(sumatoria)
varianza = sumatoria_2 / sumatoria.size
varianza

75837.38909999999

In [22]:
arreglo_6 = np.random.randn(2, 4)
arreglo_6

array([[-1.88900722, -0.60639138,  0.38763402, -2.54934407],
       [ 1.778554  ,  0.04476541,  0.39151556,  0.206369  ]])